# Generated by Django 4.2 on 2026-01-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administration.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administration.classe')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMemoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('encadreur', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_stage', models.CharField(blank=True, max_length=150, null=True)),
                ('is_theme_valide', models.BooleanField(default=False)),
                ('is_soutenu', models.BooleanField(default=False)),
                ('is_semestres_valides', models.BooleanField(default=False)),
                ('is_inscription_validee', models.BooleanField(default=False)),
                ('fichier_pre_depot', models.FileField(blank=True, null=True, upload_to='depots/pre/')),
                ('is_pre_depot_fait', models.BooleanField(default=False)),
                ('fichier_post_depot', models.FileField(blank=True, null=True, upload_to='depots/post/')),
                ('is_post_depot_fait', models.BooleanField(default=False)),
                ('is_publie', models.BooleanField(default=False)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='app_gestion_interne.etudiant')),
                ('vague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administration.vague')),
            ],
        ),
    ]
