# Generated by Django 4.2 on 2026-01-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_interne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('TITULAIRE', 'Titulaire'), ('VACATAIRE', 'Vacataire')], default='TITULAIRE', max_length=15)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jurys',
            },
        ),
    ]
