# Generated by Django 4.2 on 2026-01-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administration', '0002_alter_anneescolaire_options_remove_vague_annee_and_more'),
        ('app_gestion_interne', '0002_jury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='email',
        ),
        migrations.AddField(
            model_name='jury',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurys_set', to='app_administration.departement'),
        ),
        migrations.AlterField(
            model_name='jury',
            name='specialite',
            field=models.CharField(max_length=255),
        ),
    ]
