# Generated by Django 4.2 on 2026-01-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_interne', '0003_remove_jury_email_jury_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSE', 'En attente de validation'), ('VALIDE', 'Validé par Direction'), ('REJETE', 'Rejeté'), ('PROGRAMME', 'Programmée')], default='PROPOSE', max_length=20)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('salle', models.CharField(blank=True, max_length=100, null=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='app_gestion_interne.dossiermemoire')),
                ('examinateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='app_gestion_interne.jury')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidences', to='app_gestion_interne.jury')),
                ('rapporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='app_gestion_interne.jury')),
            ],
        ),
    ]
