# Generated by Django 4.2 on 2026-01-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administration', '0002_alter_anneescolaire_options_remove_vague_annee_and_more'),
        ('app_gestion_interne', '0004_soutenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermemoire',
            name='vague',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_administration.vague'),
        ),
    ]
