# Generated by Django 4.2 on 2026-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
