# Generated by Django 4.2 on 2026-02-05 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.RemoveField(
            model_name='livre',
            name='est_disponible',
        ),
        migrations.AddField(
            model_name='livre',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='livre',
            name='fichier_numerique',
            field=models.FileField(blank=True, null=True, upload_to='livres/fichiers/', verbose_name='Fichier PDF (Optionnel)'),
        ),
        migrations.AddField(
            model_name='livre',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='livres/couvertures/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='livre',
            name='is_publie',
            field=models.BooleanField(default=True, verbose_name='Est publié ?'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.CreateModel(
            name='JournalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIVRE_AJOUT', 'Ajout de livre'), ('LIVRE_MODIF', 'Modification de livre'), ('LIVRE_SUPP', 'Suppression de livre'), ('MEMOIRE_PUBLI', 'Publication de mémoire')], max_length=30)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_biblio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
