# Generated by Django 4.2 on 2026-02-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliotheque', '0002_alter_livre_options_remove_livre_est_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='journaloperation',
            name='action',
            field=models.CharField(choices=[('LIVRE_AJOUT', 'Ajout de livre'), ('LIVRE_MODIF', 'Modification de livre'), ('LIVRE_SUPP', 'Suppression de livre'), ('CAT_AJOUT', 'Ajout de catégorie'), ('MEMOIRE_PUBLI', 'Publication de mémoire')], max_length=30),
        ),
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='app_bibliotheque.categorie', verbose_name='Catégorie'),
        ),
    ]
