# Generated by Django 4.2 on 2026-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliotheque', '0003_categorie_alter_journaloperation_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
