# Generated by Django 4.2 on 2026-02-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DE', 'Directeur des Etudes'), ('CHEF_DEPT', 'Chef de Departement'), ('SCOLARITE', 'Scolarite'), ('COMPTABLE', 'Comptable'), ('SURVEILLANT', 'Surveillant'), ('BIBLIO', 'Bibliothecaire'), ('ETUDIANT', 'Etudiant')], max_length=20),
        ),
    ]
