# Generated by Django 4.2 on 2026-01-12 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'ordering': ['-libelle'], 'verbose_name': 'Année Scolaire'},
        ),
        migrations.RemoveField(
            model_name='vague',
            name='annee',
        ),
        migrations.AddField(
            model_name='vague',
            name='annees_concernees',
            field=models.ManyToManyField(related_name='vagues', to='app_administration.anneescolaire'),
        ),
        migrations.AddField(
            model_name='vague',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vague',
            name='est_cloturee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vague',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
    ]
