# Generated by Django 4.2 on 2026-01-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administration', '0002_alter_anneescolaire_options_remove_vague_annee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureVagueDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cloturee', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administration.departement')),
                ('vague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administration.vague')),
            ],
            options={
                'unique_together': {('vague', 'departement')},
            },
        ),
    ]
