# Generated by Django 4.2 on 2026-02-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administration', '0003_cloturevaguedepartement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vague',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagues', to='app_administration.departement'),
        ),
    ]
